# Generated by Django 3.0.2 on 2020-01-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyth_app', '0002_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
